development:
  url: neo4j://localhost:7687

test:
  url: neo4j://localhost:7688

production:
  url:
    - neo4j://core1:7687
    - neo4j://core2:7687
    - neo4j://core3:7687
  username: neo4j
  password: password
